# Generated by Django 3.2.10 on 2021-12-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='content',
        ),
    ]
