# Generated by Django 3.2.10 on 2022-01-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='title',
        ),
        migrations.AddField(
            model_name='config',
            name='accuracy',
            field=models.CharField(default='true', max_length=100),
        ),
        migrations.AddField(
            model_name='config',
            name='diagram',
            field=models.CharField(default='bar', max_length=100),
        ),
        migrations.AddField(
            model_name='config',
            name='dropout',
            field=models.CharField(default='0.5', max_length=100),
        ),
    ]
