# Generated by Django 3.2.10 on 2022-01-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220114_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='accuracy',
            field=models.CharField(default='false', max_length=100),
        ),
    ]
